---
# You timezone
timezone: "Europe/Berlin"

# User pi's password.
# Need to be hashed as coming from 'mkpasswd'. Can be omitted, then the default password ('raspberry') is used
user:
 password: "hashed password"

# Default values

debug_level: 2
