---
- name: Deploy feeder to docker swarm
  hosts: master
  gather_facts: yes
  remote_user: pi
  become: true
  become_method: sudo
  tasks:
     - name: Transfer the script
       copy: src=Ressources/feeder_stack.yml dest=/home/pi mode=0777

     - name: Execute the script
       command: docker stack deploy -c /home/pi/feeder_stack.yml feeder


