---
- name: Setup Raspberry Pi Base cluster devices
  hosts: clusterlab
  gather_facts: yes
  remote_user: pi
  become: true
  become_method: sudo
  vars_files:
    - config.yml

  roles:
    - controll
