- name: Add apt-transport-https
  apt:
    name: 'apt-transport-https'
    state: present
    force: yes

- name: Update APT package cache and upgrade
  apt:
    update_cache: yes
    autoremove: yes
    upgrade: yes

- name: Install docker
#  # Use recommended docker installation shell script
  shell: curl -sSL https://get.docker.com | sh

- name: Install Packages
  apt:
    name: ['hdparm', 'iperf', 'mtr-tiny', 'bridge-utils', 'socat', 'jq', 'vim','dnsutils', 'nfs-common', 'rpcbind', 'nfs-kernel-server']
    force: yes
    state: present

